services:
  ml_fastapi:
    build:
      context: ./ML
    container_name: ml-fastapi
    ports:
      - "9000:9000"
    env_file:
      - ./ML/configs/.env
    environment:
      - MQTT_HOST=mqtt_broker
      - MQTT_PORT=1883
    networks:
      - app-network

  server_node:
    build:
      context: ./Server
    container_name: server-node
    ports:
      - "8000:8000"
    env_file:
      - ./Server/configs/.env
    environment:
      - ML_SERVICE_URL=http://ml_fastapi:9000
      - MQTT_HOST=mqtt_broker
      - MQTT_PORT=1883
    networks:
      - app-network

  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - app-network
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

networks:
  app-network:
    driver: bridge
