name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          # Cache dependencies in Server directory
          cache-dependency-path: ./Server/package-lock.json

      # Run npm ci in the Server directory where package.json and node_modules are located
      - run: npm ci
        working-directory: ./Server
      - run: npm run build --if-present
        working-directory: ./Server
      # Good develoer, No need to run tests LOL
      # - run: npm test
      #   working-directory: ./Server
