name: Bump Version

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          ref: ${{ github.event.pull_request.merge_commit_sha || github.sha }}

      - name: Set version bump type
        id: set-bump-type
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
            if [[ "${{ github.head_ref }}" == hotfix/* || "${{ github.head_ref }}" == fix/* ]]; then
              echo "DEFAULT_BUMP=patch" >> $GITHUB_ENV
            else
              echo "DEFAULT_BUMP=minor" >> $GITHUB_ENV
            fi
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.event.before }}" != "${{ github.event.after }}" ]]; then
            echo "DEFAULT_BUMP=patch" >> $GITHUB_ENV # Default for force pushes
          else
            echo "SKIP_BUMP=true" >> $GITHUB_ENV # Skip bump for normal pushes
          fi

      - name: Set version bump type
        id: set-bump-type
        run: |
          if [[ "${{ github.head_ref }}" == hotfix/* || "${{ github.head_ref }}" == fix/* ]]; then
            echo "DEFAULT_BUMP=patch" >> $GITHUB_ENV
          else
            echo "DEFAULT_BUMP=minor" >> $GITHUB_ENV
          fi

      - name: Bump version and push tag
        if:
          (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
          (github.event_name == 'push' && ${{ env.SKIP_BUMP }} != 'true')
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          PRERELEASE: false
          DEFAULT_BUMP: ${{ env.DEFAULT_BUMP }}
